---
version: "3"
services:
  misp-db:
    image: mysql/mysql-server:5.7
    restart: ${RESTART_POLICY}
    volumes:
      - ${DATA_DIR}/data/misp/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-misp}
      - MYSQL_USER=${MYSQL_USER:-mysql}
      - MYSQL_PASSWORD=${MYSQL_PASS:-mysql}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS:-mysql}
    networks:
      - mthc

  misp-web:
    build: apps/misp-docker/web
    depends_on:
      - misp-db
    image: misp:latest
    restart: ${RESTART_POLICY}
    volumes:
      - ./apps/misp-docker/web/wait-for-it.sh:/usr/local/bin/wait-for-it.sh:ro
      - /dev/urandom/:/dev/random
      - ${DATA_DIR}/data/misp/web:/var/www/MISP
    environment:
      - MYSQL_HOST=misp-db
      - MYSQL_DATABASE=${MYSQL_DATABASE:-misp}
      - MYSQL_USER=${MYSQL_USER:-mysql}
      - MYSQL_PASSWORD=${MYSQL_PASS:-mysql}
      - MISP_ADMIN_EMAIL=${MISP_ADMIN_EMAIL:-admin@admin.test}
      - MISP_ADMIN_PASSPHRASE=${MISP_ADMIN_PASSPHRASE:-admin}
      - MISP_BASEURL=https://misp.${DOMAIN}
      - POSTFIX_RELAY_HOST=relay.fqdn
      - TIMEZONE=America/New_York
    networks:
      - mthc
      - hms-docker_traefik_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.misp.rule=Host(`misp.${DOMAIN}`)
      - traefik.http.routers.misp.middlewares=internal-ipwhitelist
      - traefik.http.services.misp.loadbalancer.server.port=80
    entrypoint: "wait-for-it.sh -t 0 -h misp-db -p 3306 -- /run.sh"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    restart: ${RESTART_POLICY}
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=hive
      - discovery.type=single-node
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=100000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - mthc

  cortex:
    image: thehiveproject/cortex:latest
    restart: ${RESTART_POLICY}
    depends_on:
      - elasticsearch
    volumes:
      - ./conf/cortex.conf:/etc/cortex/application.conf
      - ./apps/Cortex-Analyzers:/opt/Cortex-Analyzers
      - ${DATA_DIR}/data/cortex/:/data
    networks:
      - mthc
      - hms-docker_traefik_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.cortex.rule=Host(`cortex.${DOMAIN}`)
      - traefik.http.routers.cortex.middlewares=internal-ipwhitelist
      - traefik.http.services.cortex.loadbalancer.server.port=9001

  thehive:
    image: thehiveproject/thehive:latest
    restart: ${RESTART_POLICY}
    depends_on:
      - elasticsearch
      - cortex
    volumes:
      - ./conf/thehive.conf:/etc/thehive/application.conf
    networks:
      - mthc
      - hms-docker_traefik_net
    command: --cortex-key ${CORTEX_KEY}
    labels:
      - traefik.enable=true
      - traefik.http.routers.thehive.rule=Host(`thehive.${DOMAIN}`)
      - traefik.http.routers.thehive.middlewares=internal-ipwhitelist
      - traefik.http.services.thehive.loadbalancer.server.port=9000

networks:
  mthc:
    driver: bridge
  hms-docker_traefik_net:
    external: true

volumes:
  elasticsearch:
    driver: local
